version: "3"

services:
  app:
    build: ./app
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app:cached
      - ./app_tmp:/tmp:cached
    ports:
      - 4567:4000 # for web application
    command: npm run dev
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      PORT: 4000
      DATABASE_URL: postgres://root:root@postgres:5432/k-next?schema=public

  postgres:
    image: postgres:16
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:cached
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2023-02-10T18-48-39Z
    volumes:
      - ./minio/data:/export:cached
      - ./minio/config:/root/.minio:cached
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio_secret_key
    command: minio server /export --console-address :9001
