version: "3"

services:
  app:
    build: ./app
    stdin_open: true
    tty: true
    volumes: &arcturus-volumes
      - ./app:/app:cached
    ports:
      - 4567:4000 # for web application
    command: npm run dev
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PORT: 4000
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      LOCAL_S3_ENDPOINT: http://s3:9000
      LOCAL_S3_ACCESS_KEY: minio
      LOCAL_S3_SECRET_KEY: minio_secret_key

  mysql:
    image: mysql/mysql-server:8.0
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  s3:
    image: minio/minio:RELEASE.2023-02-10T18-48-39Z
    volumes:
      - ./minio/data:/export:cached
      - ./minio/config:/root/.minio:cached
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio_secret_key
    command: minio server /export --console-address :9001
